# Generated by Django 5.2.7 on 2026-03-22 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('target_type', models.CharField(choices=[('dockerfile', 'Dockerfile'), ('docker-compose', 'Docker Compose')], default='docker-compose', max_length=32)),
                ('output_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='NamedVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('driver', models.CharField(blank=True, max_length=100)),
                ('external', models.BooleanField(default=False)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('driver_opts', models.JSONField(blank=True, default=dict)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='named_volumes', to='generator.configproject')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('project', 'name'), name='uniq_named_volume_per_project')],
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('driver', models.CharField(blank=True, max_length=100)),
                ('external', models.BooleanField(default=False)),
                ('attachable', models.BooleanField(default=False)),
                ('internal', models.BooleanField(default=False)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('driver_opts', models.JSONField(blank=True, default=dict)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='generator.configproject')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('project', 'name'), name='uniq_network_per_project')],
            },
        ),
        migrations.CreateModel(
            name='ProjectOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='generator.configproject')),
            ],
            options={
                'ordering': ['key'],
                'constraints': [models.UniqueConstraint(fields=('project', 'key'), name='uniq_project_option_key')],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.CharField(blank=True, max_length=255)),
                ('build_context', models.CharField(blank=True, max_length=255)),
                ('container_name', models.CharField(blank=True, max_length=120)),
                ('command', models.CharField(blank=True, max_length=255)),
                ('restart_policy', models.CharField(blank=True, max_length=50)),
                ('ports', models.JSONField(blank=True, default=list)),
                ('volumes', models.JSONField(blank=True, default=list)),
                ('environment', models.JSONField(blank=True, default=dict)),
                ('depends_on', models.JSONField(blank=True, default=list)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='generator.configproject')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('project', 'name'), name='uniq_service_per_project')],
            },
        ),
    ]
